import {
  CancelRunningTask,
  CheckScreenCapturePermission,
  ClearResume,
  GetDomainCategories,
  GetInitStatus,
  GetModels,
  GetProfileModels,
  GetScreenshotPreview,
  GetSettings,
  MoveWindow,
  OpenScreenCaptureSettings,
  ParseResume,
  RemoveFocus,
  RequestScreenCapturePermission,
  RestoreFocus,
  SaveImageToFile,
  ScrollContent,
  SelectResume,
  SetWindowAlwaysOnTop,
  StartRecordingKey,
  StopRecordingKey,
  TestConnection,
  TestModelProfile,
  TestTranscriptionConnection,
  ToggleClickThrough,
  ToggleMinimizeWindow,
  ToggleVisibility,
  TriggerSolve,
  TriggerScreenshot,
  TriggerSend,
  RemoveScreenshot,
  ClearScreenshots,
  UpdateSettings,
  SetWorkMode,
  StartInterviewSession,
  StopInterviewSession,
  ToggleInterviewListening,
  CancelInterviewAnswer,
  EditInterviewQuestion,
  SubmitInterviewQuestion,
  GetInterviewStatus,
  ListInterviewSessions,
  GetInterviewTimeline,
  OpenInterviewMarkdown,
  OpenInterviewRecordDirectory,
  SelectKnowledgeFiles,
  IndexKnowledgeFiles,
  ListKnowledgeDocuments,
  DeleteKnowledgeDocument,
  SearchKnowledge,
  SetKnowledgeAnswerMode,
  ReindexKnowledgeDocuments,
  SelectKnowledgeDirectory,
  IndexKnowledgeDirectory,
  GetKnowledgeStoragePath,
  SaveKnowledgeNote,
} from '../../wailsjs/go/app/App'

import { Quit } from '../../wailsjs/runtime/runtime'

export const api = {
  getSettings: () => GetSettings(),
  syncSettings: (json) => UpdateSettings(json),
  updateSettings: (json) => UpdateSettings(json),
  setWorkMode: (mode) => SetWorkMode(mode),

  getModels: (apiKey, baseURL, provider) => GetModels(apiKey, baseURL, provider),
  getProfileModels: (mode, apiKey, baseURL, provider) => GetProfileModels(mode, apiKey, baseURL, provider),
  testConnection: (apiKey, baseURL, provider, model) => TestConnection(apiKey, baseURL, provider, model),
  testModelProfile: (mode, apiKey, baseURL, provider, model, protocol, thinkingMode, reasoningLevel) => TestModelProfile(mode, apiKey, baseURL, provider, model, protocol, thinkingMode, reasoningLevel),
  testTranscriptionConnection: (apiKey, model, endpoint, language, engine) => TestTranscriptionConnection(apiKey, model, endpoint, language, engine),

  startInterviewSession: () => StartInterviewSession(),
  stopInterviewSession: () => StopInterviewSession(),
  toggleInterviewListening: () => ToggleInterviewListening(),
  cancelInterviewAnswer: () => CancelInterviewAnswer(),
  editInterviewQuestion: (text) => EditInterviewQuestion(text),
  submitInterviewQuestion: () => SubmitInterviewQuestion(),
  getInterviewStatus: () => GetInterviewStatus(),
  listInterviewSessions: (limit = 50) => ListInterviewSessions(limit),
  getInterviewTimeline: (sessionId, before = '', limit = 50) => GetInterviewTimeline(sessionId, before, limit),
  openInterviewMarkdown: (sessionId) => OpenInterviewMarkdown(sessionId),
  openInterviewRecordDirectory: () => OpenInterviewRecordDirectory(),
  selectKnowledgeFiles: () => SelectKnowledgeFiles(),
  indexKnowledgeFiles: (paths) => IndexKnowledgeFiles(paths),
  listKnowledgeDocuments: () => ListKnowledgeDocuments(),
  deleteKnowledgeDocument: (path) => DeleteKnowledgeDocument(path),
  searchKnowledge: (query) => SearchKnowledge(query),
  setKnowledgeAnswerMode: (mode) => SetKnowledgeAnswerMode(mode),
  reindexKnowledgeDocuments: () => ReindexKnowledgeDocuments(),
  selectKnowledgeDirectory: () => SelectKnowledgeDirectory(),
  indexKnowledgeDirectory: (path) => IndexKnowledgeDirectory(path),
  getKnowledgeStoragePath: () => GetKnowledgeStoragePath(),
  saveKnowledgeNote: (title, content) => SaveKnowledgeNote(title, content),

  triggerSolve: () => TriggerSolve(),
  triggerScreenshot: () => TriggerScreenshot(),
  triggerSend: () => TriggerSend(),
  removeScreenshot: (index) => RemoveScreenshot(index),
  clearScreenshots: () => ClearScreenshots(),
  cancelTask: () => CancelRunningTask(),

  startRecordingKey: (action) => StartRecordingKey(action),
  stopRecordingKey: () => StopRecordingKey(),

  selectResume: () => SelectResume(),
  clearResume: () => ClearResume(),
  parseResume: () => ParseResume(),

  restoreFocus: () => RestoreFocus(),
  removeFocus: () => RemoveFocus(),
  moveWindow: (x, y) => MoveWindow(x, y),
  scrollContent: (dir) => ScrollContent(dir),
  setAlwaysOnTop: (v) => SetWindowAlwaysOnTop(v),
  toggleVisibility: () => ToggleVisibility(),
  toggleClickThrough: () => ToggleClickThrough(),
  toggleMinimizeWindow: () => ToggleMinimizeWindow(),
  quit: () => Quit(),

  getInitStatus: () => GetInitStatus(),
  getDomainCategories: () => GetDomainCategories(),

  getScreenshotPreview: (q, s, g, n, m) => GetScreenshotPreview(q, s, g, n, m),
  checkScreenCapturePermission: () => CheckScreenCapturePermission(),
  requestScreenCapturePermission: () => RequestScreenCapturePermission(),
  openScreenCaptureSettings: () => OpenScreenCaptureSettings(),

  saveImageToFile: (b64) => SaveImageToFile(b64),
}
