// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {interview} from '../models';
import {interviewhistory} from '../models';
import {screen} from '../models';
import {config} from '../models';
import {knowledge} from '../models';

export function CancelInterviewAnswer():Promise<void>;

export function CancelRunningTask():Promise<boolean>;

export function CheckMicrophoneAccess():Promise<number>;

export function CheckScreenCapturePermission():Promise<boolean>;

export function ClearResume():Promise<void>;

export function ClearScreenshots():Promise<void>;

export function CopyCode():Promise<void>;

export function DeleteKnowledgeDocument(arg1:string):Promise<void>;

export function EditInterviewQuestion(arg1:string):Promise<void>;

export function EmitEvent(arg1:string,arg2:Array<any>):Promise<void>;

export function GetDomainCategories():Promise<Array<domain.Category>>;

export function GetInitStatus():Promise<string>;

export function GetInterviewStatus():Promise<interview.Status>;

export function GetInterviewTimeline(arg1:string,arg2:string,arg3:number):Promise<Array<interviewhistory.Message>>;

export function GetKnowledgeStoragePath():Promise<string>;

export function GetModels(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function GetProfileModels(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function GetResumePDF():Promise<string>;

export function GetScreenshotPreview(arg1:number,arg2:number,arg3:boolean,arg4:boolean,arg5:string):Promise<screen.PreviewResult>;

export function GetSettings():Promise<config.Config>;

export function IndexKnowledgeDirectory(arg1:string):Promise<void>;

export function IndexKnowledgeFiles(arg1:Array<string>):Promise<void>;

export function IsInterruptThinkingEnabled():Promise<boolean>;

export function ListInterviewSessions(arg1:number):Promise<Array<interviewhistory.Session>>;

export function ListKnowledgeDocuments():Promise<Array<knowledge.Document>>;

export function MoveWindow(arg1:number,arg2:number):Promise<void>;

export function OpenInterviewMarkdown(arg1:string):Promise<void>;

export function OpenInterviewRecordDirectory():Promise<void>;

export function OpenMicrophoneSettings():Promise<void>;

export function OpenScreenCaptureSettings():Promise<void>;

export function ParseResume():Promise<string>;

export function ReindexKnowledgeDocuments():Promise<void>;

export function RemoveFocus():Promise<void>;

export function RemoveLastScreenshot():Promise<void>;

export function RemoveScreenshot(arg1:number):Promise<void>;

export function RequestMicrophoneAccess():Promise<void>;

export function RequestScreenCapturePermission():Promise<boolean>;

export function RestoreFocus():Promise<void>;

export function SaveImageToFile(arg1:string):Promise<boolean>;

export function SaveKnowledgeNote(arg1:string,arg2:string):Promise<string>;

export function ScrollContent(arg1:string):Promise<void>;

export function SearchKnowledge(arg1:string):Promise<Array<knowledge.SearchResult>>;

export function SelectKnowledgeDirectory():Promise<string>;

export function SelectKnowledgeFiles():Promise<Array<string>>;

export function SelectResume():Promise<string>;

export function SetKnowledgeAnswerMode(arg1:string):Promise<string>;

export function SetWindowAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetWorkMode(arg1:string):Promise<string>;

export function Show():Promise<void>;

export function StartInterviewSession():Promise<string>;

export function StartRecordingKey(arg1:string):Promise<void>;

export function StopInterviewSession():Promise<void>;

export function StopRecordingKey():Promise<void>;

export function SubmitInterviewQuestion():Promise<void>;

export function TestConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function TestModelProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<string>;

export function TestTranscriptionConnection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ToggleClickThrough():Promise<void>;

export function ToggleInterviewListening():Promise<string>;

export function ToggleMinimizeWindow():Promise<void>;

export function ToggleVisibility():Promise<void>;

export function ToggleWorkMode():Promise<void>;

export function TriggerCancel():Promise<void>;

export function TriggerDeleteScreenshot():Promise<void>;

export function TriggerScreenshot():Promise<void>;

export function TriggerSend():Promise<void>;

export function TriggerSolve():Promise<void>;

export function UpdateSettings(arg1:string):Promise<string>;
