// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelInterviewAnswer() {
  return window['go']['app']['App']['CancelInterviewAnswer']();
}

export function CancelRunningTask() {
  return window['go']['app']['App']['CancelRunningTask']();
}

export function CheckMicrophoneAccess() {
  return window['go']['app']['App']['CheckMicrophoneAccess']();
}

export function CheckScreenCapturePermission() {
  return window['go']['app']['App']['CheckScreenCapturePermission']();
}

export function ClearResume() {
  return window['go']['app']['App']['ClearResume']();
}

export function ClearScreenshots() {
  return window['go']['app']['App']['ClearScreenshots']();
}

export function CopyCode() {
  return window['go']['app']['App']['CopyCode']();
}

export function DeleteKnowledgeDocument(arg1) {
  return window['go']['app']['App']['DeleteKnowledgeDocument'](arg1);
}

export function EditInterviewQuestion(arg1) {
  return window['go']['app']['App']['EditInterviewQuestion'](arg1);
}

export function EmitEvent(arg1, arg2) {
  return window['go']['app']['App']['EmitEvent'](arg1, arg2);
}

export function GetDomainCategories() {
  return window['go']['app']['App']['GetDomainCategories']();
}

export function GetInitStatus() {
  return window['go']['app']['App']['GetInitStatus']();
}

export function GetInterviewStatus() {
  return window['go']['app']['App']['GetInterviewStatus']();
}

export function GetInterviewTimeline(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetInterviewTimeline'](arg1, arg2, arg3);
}

export function GetKnowledgeStoragePath() {
  return window['go']['app']['App']['GetKnowledgeStoragePath']();
}

export function GetModels(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetModels'](arg1, arg2, arg3);
}

export function GetProfileModels(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetProfileModels'](arg1, arg2, arg3, arg4);
}

export function GetResumePDF() {
  return window['go']['app']['App']['GetResumePDF']();
}

export function GetScreenshotPreview(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetScreenshotPreview'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function IndexKnowledgeDirectory(arg1) {
  return window['go']['app']['App']['IndexKnowledgeDirectory'](arg1);
}

export function IndexKnowledgeFiles(arg1) {
  return window['go']['app']['App']['IndexKnowledgeFiles'](arg1);
}

export function IsInterruptThinkingEnabled() {
  return window['go']['app']['App']['IsInterruptThinkingEnabled']();
}

export function ListInterviewSessions(arg1) {
  return window['go']['app']['App']['ListInterviewSessions'](arg1);
}

export function ListKnowledgeDocuments() {
  return window['go']['app']['App']['ListKnowledgeDocuments']();
}

export function MoveWindow(arg1, arg2) {
  return window['go']['app']['App']['MoveWindow'](arg1, arg2);
}

export function OpenInterviewMarkdown(arg1) {
  return window['go']['app']['App']['OpenInterviewMarkdown'](arg1);
}

export function OpenInterviewRecordDirectory() {
  return window['go']['app']['App']['OpenInterviewRecordDirectory']();
}

export function OpenMicrophoneSettings() {
  return window['go']['app']['App']['OpenMicrophoneSettings']();
}

export function OpenScreenCaptureSettings() {
  return window['go']['app']['App']['OpenScreenCaptureSettings']();
}

export function ParseResume() {
  return window['go']['app']['App']['ParseResume']();
}

export function ReindexKnowledgeDocuments() {
  return window['go']['app']['App']['ReindexKnowledgeDocuments']();
}

export function RemoveFocus() {
  return window['go']['app']['App']['RemoveFocus']();
}

export function RemoveLastScreenshot() {
  return window['go']['app']['App']['RemoveLastScreenshot']();
}

export function RemoveScreenshot(arg1) {
  return window['go']['app']['App']['RemoveScreenshot'](arg1);
}

export function RequestMicrophoneAccess() {
  return window['go']['app']['App']['RequestMicrophoneAccess']();
}

export function RequestScreenCapturePermission() {
  return window['go']['app']['App']['RequestScreenCapturePermission']();
}

export function RestoreFocus() {
  return window['go']['app']['App']['RestoreFocus']();
}

export function SaveImageToFile(arg1) {
  return window['go']['app']['App']['SaveImageToFile'](arg1);
}

export function SaveKnowledgeNote(arg1, arg2) {
  return window['go']['app']['App']['SaveKnowledgeNote'](arg1, arg2);
}

export function ScrollContent(arg1) {
  return window['go']['app']['App']['ScrollContent'](arg1);
}

export function SearchKnowledge(arg1) {
  return window['go']['app']['App']['SearchKnowledge'](arg1);
}

export function SelectKnowledgeDirectory() {
  return window['go']['app']['App']['SelectKnowledgeDirectory']();
}

export function SelectKnowledgeFiles() {
  return window['go']['app']['App']['SelectKnowledgeFiles']();
}

export function SelectResume() {
  return window['go']['app']['App']['SelectResume']();
}

export function SetKnowledgeAnswerMode(arg1) {
  return window['go']['app']['App']['SetKnowledgeAnswerMode'](arg1);
}

export function SetWindowAlwaysOnTop(arg1) {
  return window['go']['app']['App']['SetWindowAlwaysOnTop'](arg1);
}

export function SetWorkMode(arg1) {
  return window['go']['app']['App']['SetWorkMode'](arg1);
}

export function Show() {
  return window['go']['app']['App']['Show']();
}

export function StartInterviewSession() {
  return window['go']['app']['App']['StartInterviewSession']();
}

export function StartRecordingKey(arg1) {
  return window['go']['app']['App']['StartRecordingKey'](arg1);
}

export function StopInterviewSession() {
  return window['go']['app']['App']['StopInterviewSession']();
}

export function StopRecordingKey() {
  return window['go']['app']['App']['StopRecordingKey']();
}

export function SubmitInterviewQuestion() {
  return window['go']['app']['App']['SubmitInterviewQuestion']();
}

export function TestConnection(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['TestConnection'](arg1, arg2, arg3, arg4);
}

export function TestModelProfile(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['TestModelProfile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function TestTranscriptionConnection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['TestTranscriptionConnection'](arg1, arg2, arg3, arg4, arg5);
}

export function ToggleClickThrough() {
  return window['go']['app']['App']['ToggleClickThrough']();
}

export function ToggleInterviewListening() {
  return window['go']['app']['App']['ToggleInterviewListening']();
}

export function ToggleMinimizeWindow() {
  return window['go']['app']['App']['ToggleMinimizeWindow']();
}

export function ToggleVisibility() {
  return window['go']['app']['App']['ToggleVisibility']();
}

export function ToggleWorkMode() {
  return window['go']['app']['App']['ToggleWorkMode']();
}

export function TriggerCancel() {
  return window['go']['app']['App']['TriggerCancel']();
}

export function TriggerDeleteScreenshot() {
  return window['go']['app']['App']['TriggerDeleteScreenshot']();
}

export function TriggerScreenshot() {
  return window['go']['app']['App']['TriggerScreenshot']();
}

export function TriggerSend() {
  return window['go']['app']['App']['TriggerSend']();
}

export function TriggerSolve() {
  return window['go']['app']['App']['TriggerSolve']();
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}
